- name: build docker images
  hosts: all
  vars_files:
  - vars.yaml
  vars:
    repo_dir: '{{ stage_dir }}/amigo'

  tasks:
  - name: Checkout repos
    git:
     repo: '{{ repo }}'
     dest: '{{ repo_dir }}'
     version: '{{ branch }}'
     force: yes 

  - name: build image
    shell: "docker build -f {{ repo_dir }}/docker/Dockerfile -t 'amigo:{{ tag }}' {{ repo_dir }}"
