version: '3'
services:
  amigo:
    hostname: amigo
    container_name: amigo 
    image: amigo:{{ tag }}
    environment:
       GULP_INSTALL: {{ GULP_INSTALL }} 
    volumes:
      - {{ stage_dir }}/srv-solr-data:/srv/solr/data
      - {{ repo_dir }}:/srv/amigo
    restart: unless-stopped

  apache_amigo:
    hostname: apache_amigo
    container_name: apache_amigo
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - {{ stage_dir }}//httpd.conf:/usr/local/apache2/conf/httpd.conf
      - {{ stage_dir }}/httpd-vhosts-amigo.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - "80:80"
    depends_on:
      - amigo

