- hosts: all
  vars_files:
  - vars.yaml

  tasks:
  - name: Check if index exists
    stat:
      path: '{{ stage_dir }}/srv-solr-data/index'
    register: index_result

  - name: Create Solr Index
    shell: | 
         docker run --rm \
                -e GOLR_SOLR_MEMORY=4G \
                -e GOLR_LOADER_MEMORY=8G \
                -e GOLR_INPUT_ONTOLOGIES=http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl \
                -v '{{ stage_dir }}/srv-solr-data:/srv/solr/data' \
                -t geneontology/golr-autoindex-ontology 
    args:
      executable: /bin/bash
    when: not index_result.stat.exists

  - name: install templates
    template:
      src: '{{ repo_dir }}/provision/{{ item.file }}'
      dest: '{{ stage_dir }}/{{ item.dir }}'
    with_items:
      - { file: 'docker-compose.yaml', dir: '' }
