####
#### The annotation description file for GOlr and AmiGO.
####
id: bbop_ann
schema_generating: true
description: A description of annotations for GOlr and AmiGO.
display_name: Annotations
document_category: annotation
weight: 20
boost_weights: annotation_class^2.0 annotation_class_label^1.0 bioentity^2.0 bioentity_label^1.0 bioentity_name^1.0 annotation_extension_class^2.0 annotation_extension_class_label^1.0 reference^1.0 panther_family^1.0 panther_family_label^1.0 bioentity_isoform^1.0
result_weights: bioentity^7.0 bioentity_name^6.0 qualifier^5.0 annotation_class^4.7 annotation_extension_json^4.5 source^4.0 taxon^3.0 evidence_type^2.5 evidence_with^2.0 panther_family^1.5 bioentity_isoform^0.5 reference^0.25
filter_weights: source^7.0 assigned_by^6.5 aspect^6.25 evidence_type_closure^6.0 panther_family_label^5.5 taxon_closure_label^5.0 annotation_class_label^4.5 regulates_closure_label^3.0 annotation_extension_class_closure_label^2.0
fields:
  - id: id
    description: A unique (and internal) combination of bioentity and ontology class.
    display_name: Acc
    type: string
    property: []
  - id: source
    description: "GAF column 1 (database source)."
    display_name: Source
    type: string
    property: []
  - id: type
    description: "GAF column 12 (type class id)."
    display_name: Type class id
    type: string
    property: []
#   - id: type_label
#     description: "GAF column 12 (type class label)"
#     display_name: Type class label
#     type: string
#     property: []
  - id: date
    description: "GAF column 14 (date of assignment)."
    display_name: Date
    type: string
    property: []
  - id: assigned_by
    description: "GAF column 15 (assigned by)."
    display_name: Assigned by
    type: string
    property: []
#   - id: type_closure
#     description: "Derived from c12 + SO."
#     display_name: Type closure
#     type: string
#     cardinality: multi
#     property: []
#   - id: type_closure_label
#     description: "Derived from c12 + SO."
#     display_name: Type label closure
#     type: string
#     cardinality: multi
#     property: []
  - id: taxon
    description: "GAF column 13 (taxon)."
    display_name: Taxon
    type: string
    property: []
  - id: taxon_label
    description: "Taxon derived from GAF column 13 and ncbi_taxonomy.obo."
    display_name: Taxon
    type: string
    property: []
    searchable: true
  - id: taxon_closure
    description: "Taxon IDs derived from GAF column 13 and ncbi_taxonomy.obo."
    display_name: Taxon (IDs)
    type: string
    cardinality: multi
    property: []
  - id: taxon_closure_label
    description: "Taxon label closure derived from GAF column 13 and ncbi_taxonomy.obo."
    display_name: Taxon
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: isa_partof_closure
    description: "Closure of ids/accs over isa and partof."
    display_name: Involved in (IDs)
    type: string
    cardinality: multi
    property: []
  - id: isa_partof_closure_label
    description: "Closure of labels over isa and partof."
    display_name: Involved in
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: regulates_closure
    description: "Closure of ids/accs over regulates."
    display_name: Inferred annotation (IDs)
    type: string
    cardinality: multi
    property: []
  - id: regulates_closure_label
    description: "Closure of labels over regulates."
    display_name: Inferred annotation
    type: string
    cardinality: multi
    property: []
    searchable: true
#   - id: label
#     description: Symbol or name.
#     display_name: Label
#     type: string
#     property: []
#     searchable: true
#   - id: descriptive_name
#     description: Full name or name.
#     display_name: Full name
#     type: string
#     property: []
#     searchable: true
  - id: synonym
    description: "GAF column 11: gene product synonyms."
    display_name: Synonym
    type: string
    cardinality: multi
    property: []
#   - id: alternate_id
#     description: Any alternaitve id.
#     display_name: Alt id
#     type: string
#     cardinality: multi
#     property: []
#   - id: description
#     description: Definition.
#     display_name: Definition
#     type: string
#     property: []
#     searchable: true
#   - id: subset
#     description: Member of these named subsets.
#     display_name: Subset
#     type: string
#     cardinality: multi
#     property: []
#   - id: is_obsolete
#     description: Is this obsolete?
#     display_name: Obsolete
#     type: integer
#     property: []
#   - id: comment
#     description: Comment.
#     display_name: comment
#     type: string
# #    cardinality: multi
#     property: []
#     searchable: true
#   - id: definition_xref
#     description: DBXref for definitions.
#     display_name: Def dbxref
#     type: string
#     cardinality: multi
#     property: []
#   - id: annotation_closure
#     description: All terms associatied with GP.
#     display_name: All annotations
#     type: string
#     cardinality: multi
#     property: []
#   - id: axiom
#     description: "Each ontology entity (class or property) can be associated with multiple OWL axioms. We cache them in the index so that advanced OWL-aware clients can pull relevant information quickly. Axioms are stored in functional syntax."
#     display_name: Axiom
#     type: string
#     cardinality: multi
#     property: []
  - id: bioentity
    description: "GAF column 1 + columns 2."
    display_name: Gene/Product
    type: string
    property: []
  - id: bioentity_label
    description: "GAF column 3: bioentity label."
    display_name: Gene/product label
    type: string
    property: []
    searchable: true
  - id: bioentity_name
    description: "The full name of the gene product."
    display_name: Gene/Product name
    type: string
    property: []
    searchable: true
  - id: bioentity_internal_id
    description: "The bioentity ID used at the database of origin."
    display_name: This should not be displayed
    type: string
    property: []
    indexed: false
#   - id: bioentity_alternate_label
#     description: Alternate label.
#     display_name: Alternate label
#     type: string
#     cardinality: multi
#     property: []
#   - id: is_negated
#     description: Derived from column 4.
#     display_name: Is not
#     type: string
#     property: []
  - id: qualifier
    description: "Annotation qualifier--derived from GAF column 4."
    display_name: Qualifier
    type: string
    cardinality: multi
    property: []
  - id: annotation_class
    description: "Direct annotations (GAF column 5)."
    display_name: Direct annotation
    type: string
    property: []
  - id: annotation_class_label
    description: "Direct annotations (GAF column 5)."
    display_name: Direct annotation
    type: string
    property: []
    searchable: true
  - id: aspect
    description: "GAF column 9: Ontology aspect."
    display_name: Ontology (aspect)
    type: string
    property: []
#   - id: secondary_taxon
#     description: Acts on taxon.
#     display_name: Secondary taxon
#     type: string
#     property: []
#   - id: secondary_taxon_label
#     description: Acts on taxon.
#     display_name: Secondary taxon label
#     type: string
#     property: []
  - id: bioentity_isoform
    description: "GAF column 17: Bioentity isoform."
    display_name: Isoform
    type: string
    property: []
#   - id: bioentity_isoform_label
#     description: ???
#     display_name: Bioentity isoform label
#     type: string
#     cardinality: multi
#     property: []
  - id: evidence_type
    description: "GAF column 7: evidence type."
    display_name: Evidence
    type: string
    property: []
  - id: evidence_type_closure
    description: All evidence (evidence closure) for this annotation
    display_name: Evidence type
    type: string
    cardinality: multi
    property: []
  - id: evidence_with
    description: "GAF column 8: with/from."
    display_name: Evidence with
    type: string
    cardinality: multi
    property: []
  - id: reference
    description: "GAF column 6: database reference."
    display_name: Reference
    type: string
    cardinality: multi
    property: []
  - id: annotation_extension_class
    description: "GAF column 16: extension class for the annotation."
    display_name: Annotation extension
    type: string
    cardinality: multi
    property: []
  - id: annotation_extension_class_label
    description: ???
    display_name: Annotation extension (labels)
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: annotation_extension_class_closure
    description: ???
    display_name: Annotation extension (IDs)
    type: string
    cardinality: multi
    property: []
  - id: annotation_extension_class_closure_label
    description: ???
    display_name: Annotation extension
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: annotation_extension_json
    description: A special JSON blob for GAF column 16.
    display_name: Annotation extension
    type: string
    cardinality: multi
    property: []
  - id: panther_family
    description: PANTHER family IDs that are associated with this entity.
    display_name: PANTHER family
    type: string
    searchable: true
    property: []
  - id: panther_family_label
    description: PANTHER families that are associated with this entity.
    display_name: PANTHER family
    type: string
    searchable: true
    property: []
  # - id: phylo_graph
  #   description: JSON blob form of the phylogenic tree.
  #   display_name: This should not be displayed
  #   type: string
  #   property: []
  #   indexed: false
  ## TODO: Sleeping for now, but will re-add when the right
  ## experimental GAFs start getting loaded as well.
  # - id: phylo_ancestor_closure
  #   description: All ancestors of this entity.
  #   display_name: Phylogenic ancestors
  #   type: string
  #   cardinality: multi
  #   property: []
  # - id: phylo_descendant_closure
  #   description: All descendants of this entity.
  #   display_name: Phylogenic descendants
  #   type: string
  #   cardinality: multi
  #   property: []
