####
#### The generic that will as as the general landing search.
####
id: bbop_general
description: A generic search document to get a general overview of everything.
display_name: General
document_category: general
weight: 0
boost_weights: id^3.0 id_label^3.0 general_blob^3.0
result_weights: id^3.0 id_label^2.0 category^1.0
filter_weights: category^4.0 id^3.0
fields:
  - id: id
    description: The ID for this entity.
    display_name: ID
    type: string
    property: []
  - id: id_label
    description: The label for this entity.
    display_name: Label
    type: string
    property: []
    searchable: true
  - id: category
    description: The document category that this enitity belongs to.
    display_name: Document category
    type: string
    property: []
  - id: general_blob
    description: A hidden searchable blob document to access this item.
    display_name: Generic blob
    type: string
    property: []
    searchable: true
