####
#### The bioentity description file for GOlr and AmiGO.
####
id: bbop_family
schema_generating: true
description: Information about protein (PANTHER) families.
display_name: Protein families
document_category: family
weight: 5
boost_weights: bioentity^2.0 bioentity_label^2.0 bioentity_name^1.0 isa_partof_closure_label^1.0 regulates_closure_label^1.0 panther_family^1.0 panther_family_label^1.0 taxon_closure_label^1.0
result_weights: bioentity^8.0 bioentity_name^7.0 taxon^6.0 panther_family^5.0 type^4.0 source^3.0 annotation_class_list^2.0
filter_weights: source^7.0 type^6.0 panther_family_label^5.0 annotation_class_list_label^3.5 taxon_closure_label^4.0 isa_partof_closure_label^3.0 regulates_closure_label^2.0
fields:
  - id: id
    description: Family ID.
    display_name: Acc
    type: string
    property: []
  - id: panther_family
    description: PANTHER family IDs that are associated with this entity.
    display_name: PANTHER family
    type: string
    searchable: true
    property: []
  - id: panther_family_label
    description: PANTHER families that are associated with this entity.
    display_name: PANTHER family
    type: string
    searchable: true
    property: []
  - id: phylo_graph
    description: JSON blob form of the phylogenic tree.
    display_name: This should not be displayed
    type: string
    property: []
    indexed: false
  # - id: annotation_class_list
  #   description: "Terms directly annotated with this protein family."
  #   display_name: Annotations 
  #   type: string
  #   cardinality: multi
  #   property: []
  # - id: annotation_class_list_label
  #   description: "Terms directly annotated with this protein family."
  #   display_name: Annotations
  #   type: string
  #   cardinality: multi
  #   property: []
  # - id: panther_family
